config/routes.rb
CaciqueSnips::Application.routes.draw do
  devise_for :users

  resources :snippets

  root :to => 'snippets#index'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
   attr_accessible :title, :snippet, :language, :user, :public
   belongs_to :user

   def self.by_owner_or_public(user_id)
     where('user_id = ? or public = ?',user_id,true)
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :ensure_owner, :only => [:update,:destroy]
  def new
    @snippet = Snippet.new
  end

  def create
    snippet = Snippet.new(params[:snippet].merge!(:user => current_user))
    snippet.save
    redirect_to snippets_path
  end

  def show
    @snippet = Snippet.find(params[:id])
  end

  def index
    user_id = current_user ? current_user.id : -1
    if(params[:language])
      @snippets = Snippet.where(:language => params[:language]).by_owner_or_public(user_id)
      @selected_language = params[:language]
    else
      @snippets = Snippet.by_owner_or_public(user_id)
    end
    all_snippets = Snippet.by_owner_or_public(user_id)
    @languages = all_snippets.group_by(&:language)
  end

  def edit
    @snippet = Snippet.find(params[:id])
  end

  def destroy
    Snippet.delete(params[:id])
    redirect_to snippets_path
  end

  def update
    @snippet = Snippet.find(params[:id])
    @snippet.update_attributes(params[:snippet])
    @snippet.save
    redirect_to snippets_path
  end

  private
  def ensure_owner
    @snippet =  Snippet.find(params[:id])
    raise "Permission Error" unless @snippet.user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
  def languages
    [['java','java'],['ruby','ruby'],['javascript','javascript'],['as3','as3'],['bash','bash'],['csharp','csharp'],['cpp','cpp'],['css','css'],['delphi','delphi'],['diff','diff'],['erlang','erlang'],['javafx','javafx'],['perl','perl'],['php','php'],['plain','plain'],['powershell','powershell'],['python','python'],['scala','scala'],['sql','sql'],['vb','vb'],['xml','xml']]
  end
end

app/views/layouts/application.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Cacique Snips" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <style type="text/css">
      html,
      body {
          height: 100%;
      }
      #main {
          min-height: 100%;
          height: auto !important;
          height: 100%;
          margin: 0 auto -60px;
      }
      #push,
      #footer {
          height: 100px;
      }
      #footer {
          background-color: #f5f5f5;
          text-align: center;;
      }
      @media (max-width: 767px) {
          #footer {
              margin-left: -20px;
              margin-right: -20px;
              padding-left: 20px;
              padding-right: 20px;
          }
      }
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<header>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "cacique-snips", snippets_path,  :class => 'brand' %>
        <div class="nav-collapse collapse">
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
                Signed in as <%= current_user.email %>
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path %>
                <%= link_to "Sign in", new_user_session_path %>
            <% end %>
          </p>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
</header>
<div id="main" role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <br/>  <br/><br/><br/><br/>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <br/>
          <%= yield %>
        </div>
      </div>
    </div>
  </div> <!--! end of .container -->
  <div id="push"></div>
</div> <!--! end of #main -->
<div id="footer">
  <div class="container">
    <p class="muted credit"><%= image_tag 'cacique.png' %> Copyright (c) 2012 Cacique Technologies LTD</p>
  </div>
</div>
</body>
</html>

app/views/snippets/_form.erb
<%= form_for @snippet do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :language %>
    <%= f.select(:language, languages) %>
    <%= f.label :snippet %>
    <%= f.text_area :snippet %>
    <%= f.label :public %>
    <%= f.check_box :public %>
    <br/>
    <%= f.submit %>
<% end %>

app/views/snippets/edit.erb
New Snippet: <br/>
<%= render 'form' %>

app/views/snippets/index.erb
<% @languages.each do |language,snippets| %>
    <%= link_to  "#{language}(#{snippets.count})", snippets_path(:language => language)%>
    <br/>
 <% end %>

<br/>
<br/>

<% if @selected_language %>
<br/>Snippets in <%= @selected_language %> <br/>
<% @snippets.each do |snippet| %>
    <%= link_to snippet.title, snippet %> &nbsp;&nbsp;&nbsp;&nbsp;<%= snippet.language %><br/>
<% end %>

<br/>
<br/>
 <% end %>
<%= link_to 'Create Snippet', new_snippet_path %>

app/views/snippets/new.erb
New Snippet: <br/>
<%= render 'form' %>

app/views/snippets/show.erb
<script type="text/javascript">SyntaxHighlighter.all();</script>
<h2><%= @snippet.title %>  ( <%= @snippet.language %> )</h2>
<pre class="brush: <%= @snippet.language %>;">
 <%= @snippet.snippet %>
</pre>
<br/>
<br/>
<%= link_to 'Edit', edit_snippet_path(@snippet)%>
<%= link_to 'delete', @snippet, :confirm => "Delete?",  :method => :delete%>